import { FileSystemItem, Folder } from '@/types';

export const mockFolders: Folder[] = [
  {
    id: 'folder-1',
    name: 'Arbeit',
    color: '#FF6B6B',
    items: [],
    parentId: undefined,
  },
  {
    id: 'folder-2',
    name: 'Privat',
    color: '#4ECDC4',
    items: [],
    parentId: undefined,
  },
  {
    id: 'folder-3',
    name: 'Projekte',
    color: '#45B7D1',
    items: [],
    parentId: undefined,
  },
];

export const mockFiles: FileSystemItem[] = [
  {
    id: 'file-1',
    name: 'Präsentation.pdf',
    type: 'file',
    extension: 'pdf',
    x: 100,
    y: 150,
    parentId: undefined,
    size: 2048000,
    createdAt: new Date('2025-12-01'),
    modifiedAt: new Date('2025-12-03'),
  },
  {
    id: 'file-2',
    name: 'Urlaubsfoto.jpg',
    type: 'file',
    extension: 'jpg',
    x: 300,
    y: 200,
    parentId: undefined,
    size: 5120000,
    createdAt: new Date('2025-11-15'),
    modifiedAt: new Date('2025-11-15'),
  },
  {
    id: 'file-3',
    name: 'Notizen.txt',
    type: 'file',
    extension: 'txt',
    x: 500,
    y: 100,
    parentId: undefined,
    size: 8192,
    createdAt: new Date('2025-12-02'),
    modifiedAt: new Date('2025-12-04'),
  },
  {
    id: 'file-4',
    name: 'Budget.xlsx',
    type: 'file',
    extension: 'xlsx',
    x: 150,
    y: 400,
    parentId: undefined,
    size: 102400,
    createdAt: new Date('2025-11-20'),
    modifiedAt: new Date('2025-12-01'),
  },
  {
    id: 'file-5',
    name: 'Rezept.docx',
    type: 'file',
    extension: 'docx',
    x: 400,
    y: 450,
    parentId: undefined,
    size: 51200,
    createdAt: new Date('2025-12-03'),
    modifiedAt: new Date('2025-12-03'),
  },
];
